name: Continuous integration
on:
  push:
jobs:
  lint:
    name: Run luacheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: luacheck
        uses: nebularg/actions-luacheck@v1.1.0
        with:
          files: source
  release:
    name: Automated release
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - name: install gitman
        run: pipx install gitman
      - name: install dependencies
        run: gitman install
      - run: mkdir LibEventDispatcher
      - run: mv LibEventDispatcher.* LibEventDispatcher/
      - run: mv readme.MD LibEventDispatcher/
      - run: mv source LibEventDispatcher/
      - run: mv libs LibEventDispatcher/
      - run: ls -lahr LibEventDispatcher
      - run: zip -r LibEventDispatcher.zip LibEventDispatcher

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install dependencies for semantic-release
        run: npm ci
      - run: $(npm bin)/semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
